---
- name: apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: latest
  notify: restart dnsmasq